name: graphrag_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch>=2.1.0,<2.2.0 # PyGのCPUホイールURLとバージョンを合わせるため、>=2.1.0系統を指定
  - torchvision
  - torchaudio
  - transformers
  - scikit-learn
  - networkx
  - pybind11
  - scipy=1.12         
  - protobuf           
  - pip
  - pip:
    - sentence-transformers
    - torch-geometric
    - peft               
    - pandas             
    - ogb                
    - wandb              
    - sentencepiece      
    - pcst_fast          
    - gensim             
    - datasets           
    - pyg_lib            